### ISSUE TITLE
Stuck on "Listening for Discord IPC Calls"

### ISSUE THREAD

**Issue by Pfuenzle** [Adamaq01/vfio-discord-ipc-bridge#1]
I successfully built and ran your project, but for some reasons its not working

This is the output from the Windows guest:
`Connecting to 192.168.122.1:8765
Successfully connected to 192.168.122.1:8765
Listening for Discord IPC Calls`

This does not change, even if i restart the game and/or discord

**Comment by adamaq01** [comment]
Hello, good to see that someone is using this program haha
Can you please also send the logs of the host program ?

Also, does the game you're trying with supports Discord Rich Presence ?

**Comment by Pfuenzle** [comment]
Hi, thanks for answering so fast :D
Im happy your program exists, I was really amazed when I did not find any other program that achieves this.

Heres the Client log on Windows:
`PS C:\Users\Leon\Desktop> .\guest.exe --address 192.168.122.1
Connecting to 192.168.122.1:8765
Successfully connected to 192.168.122.1:8765
Listening for Discord IPC Calls`

And heres the Host log (on Manjaro):
`Listening on: 0.0.0.0:8765
Accepted connection 192.168.122.212:49746`

Im running the host by just executing ./host, I assume this is supposed to work like this, considering the Connection itself is working?

The game I was initially trying out was Genshin Impact, which normally shows in Discord that I am palying it and for how long i was playing it.
While writing this I just tried out League of Legends, which from what I know, offers the same Info to Discord.

League of Legends Logs:
Client:
`PS C:\Users\Leon\Desktop> .\guest.exe --address 192.168.122.1
Connecting to 192.168.122.1:8765
Successfully connected to 192.168.122.1:8765
Listening for Discord IPC Calls
Accepted connection 25e04b96-512f-4f61-9c54-e7ef65225599`

Host:
`Listening on: 0.0.0.0:8765
Accepted connection 192.168.122.212:50171
Attempting to connect to /run/user/1000/discord-ipc-0
Connected to /run/user/1000/discord-ipc-0
`

When Playing League of Legends, its showing either "In Lobby" or "In Game", instead of just "Playing" when playing Genshin Impact. 
Is it possible that "Playing Game XXX" does not count as a Rich Presence?
Thanks

**Comment by adamaq01** [comment]
I checked and unfortunately Genshin Impact doesn't support Rich Presence so yeah it couldn't work :/
Maybe there is a program that hooks into Genshin Impact and adds support for Rich Presence for the game.

I will close the issue since there is no real problem then 😅

**Comment by Pfuenzle** [comment]
Oh, then sorry this issue, I misinterpreted what rich presence meant.
And sorry again for re-opening this issue, but I thought opening another issue just for this question would be a bit overkill 😅
Would it be possible for your program to broadcast these non rich presence Infos like in genshin impact (Playing Genshin Impact etc...) to discord on the Host? Didn't find any other program that does this either. Or is it strictly for rich presence?stuff? 
Thanks

**Comment by adamaq01** [comment]
Hey, no worry, discussing does not reopen the issue :)

Unfortunately discord doesn't use RPC for detecting simple programs/games, It just scans through active processes and displays infos if it recognizes one.
Maybe there's a way to trick this and display those infos but this a bit out of this project's scope and I don't really know how we can do this.
Though I'd be happy to implement such a thing if someone finds a way to achieve this or maybe an alternative solution.

**Comment by Pfuenzle** [comment]
Oh okay, thats a whole different thing then :D
I'll try some things out, maybe I get it to work.
But im still happy I found your project, its still really helpful
